### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by Anujkrishna12** [PetervanLunteren/EcoAssist#18] opened 2023-08-02 08:30 UTC
hey, is their a way I can maintain the folder structure.?

**Comment by PetervanLunteren** [comment] 2023-08-02 08:34
@Anujkrishna12 I'm not sure what you mean with that question. Can you elaborate? Are you talking about any of the post-processing features? If so, which one?

**Comment by Anujkrishna12** [comment] 2023-08-02 09:03
Yes, in post processing features I want the images to be copied to the
respective specified folder.
attaching an image for your reference.
(ps. each grid represents a camera station and contains about 5000 images)

**Comment by PetervanLunteren** [comment] 2023-08-02 10:09
I'm still not sure what your question is and there is no image attached. But maybe the following will answer your question.

If you have precessed your images at step 2 and have arrived at step 3, you can copy your images with options 2 and 3 on the screenshot below. They will be copied to the folder you have specified at 1 in the screenshot. You can find more information in the help tab inside EcoAssist.

<img width="525" alt="Screenshot 2023-08-02 at 12 04 17" src="https://github.com/PetervanLunteren/EcoAssist/assets/85185478/d07e9c5c-45ea-4b93-b134-a20c66e21b52">

**Comment by PetervanLunteren** [comment] 2023-08-04 08:08
@Anujkrishna12 If the problem is resolved please close this issue.

**Closed** 2023-08-06 06:56 UTC
